name: integration-branch-cleanup
# Run this workflow every time a branch has been deleted. Will cause integration branch to also be removed.
on: delete
jobs:
  cleanup_integration_branch:
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0' # all branches and tags
      - name: Clean up integration branch
        run: |
          BRANCH=${{ github.event.ref }}
          echo "Running clean up for branch: $BRANCH"
          echo "Checkout integration branch: integration/$BRANCH"
          git checkout integration/$BRANCH
          echo "Removing integration branch: integration/$BRANCH"
          git push origin --delete integration/$BRANCH
          echo "Removed integration branch: integration/$BRANCH"
          echo "Clean up complete for branch: $BRANCH"
